#!/bin/bash
#
# Regression test for the MolDStruct strong-field ionization module.
#
# Runs a small water cluster through an ionizing pulse with the ADK random
# seed pinned, and checks four things:
#
#   1. the ionization event count and final charges match a stored reference
#   2. sum(charges) == number of ionization events
#   3. a run without -ionize writes no ionization output
#   4. -nt 4 -pd reproduces -nt 4 -pd with the same seed
#
# (1) is a bitwise check and is the point of the test.  The ADK draws are
# stochastic, but GMX_SFMD_SEED pins them, so any change that alters the
# physics moves these numbers.  It is only meaningful against a reference
# generated by the same build on the same machine -- a different compiler or
# optimisation level can shift the trajectory.  Regenerate with --update when
# you change the physics deliberately, and say so in the commit.
#
# (2) holds on any build: every ADK tunnelling event removes exactly one
# electron, so the total charge must equal the event count.  A failure there
# is a real bug, not a platform difference.
#
# (4) matters because each rank draws its own stream; reproducibility is per
# rank count, so the same seed at -nt 1 and -nt 4 are different realisations
# by design and are NOT compared against each other.
#
# The pulse is deliberately short and centred inside the run window.  A
# window that ends before the pulse produces zero ionization events, and then
# every run matches whatever the seed is -- the test would pass while proving
# nothing.
#
# Usage:
#   test/regression.sh [--bindir DIR] [--steps N] [--update] [--keep]
#
set -u

REPO="$(cd "$(dirname "$0")/.." && pwd)"
BINDIR="$REPO/gromacs-4.5.4-SFMD/build/src/kernel"
STEPS=2000
UPDATE=0
KEEP=0
SEED=12345

while [ $# -gt 0 ]; do
    case "$1" in
        --bindir) BINDIR="$2"; shift 2 ;;
        --steps)  STEPS="$2";  shift 2 ;;
        --update) UPDATE=1;    shift ;;
        --keep)   KEEP=1;      shift ;;
        -h|--help) sed -n '2,36p' "$0"; exit 0 ;;
        *) echo "unknown argument: $1" >&2; exit 2 ;;
    esac
done

REF="$REPO/test/reference_${STEPS}.txt"
WORK="$(mktemp -d)"
trap '[ "$KEEP" = 1 ] && echo "kept $WORK" || rm -rf "$WORK"' EXIT

for exe in grompp mdrun; do
    if [ ! -x "$BINDIR/$exe" ]; then
        echo "FAIL: $exe not found in $BINDIR (pass --bindir)" >&2
        exit 2
    fi
done

export GMXLIB="${GMXLIB:-$REPO/gromacs-4.5.4-SFMD/share/top}"
export GMX_SFMD_SEED="$SEED"

cp "$REPO/test/conf.gro" "$REPO/test/topol.top" "$WORK/"
sed "s/^nsteps.*/nsteps = $STEPS/" "$REPO/test/exp.mdp" > "$WORK/exp.mdp"
cd "$WORK" || exit 2

echo "workdir  $WORK"
echo "binaries $BINDIR"
echo "steps    $STEPS, seed $SEED"
echo

run() { if ! "$@" >>setup.log 2>&1; then echo "FAIL: $1 failed, see $WORK/setup.log" >&2; KEEP=1; exit 1; fi; }

mkdir -p simulation_output
run "$BINDIR/grompp" -f exp.mdp -c conf.gro -p topol.top -o run.tpr -po out.mdp -maxwarn 30
run "$BINDIR/mdrun" -deffnm run -s run.tpr -nt 1 -ionize

EVENTS="$(wc -l < simulation_output/transition_log.txt)"
CHARGE_SUM="$(awk '{s+=$2} END{print s+0}' simulation_output/charges.txt)"
STATS="$EVENTS $CHARGE_SUM"

FAILED=0

echo "--- 1. ionization events and total charge"
if [ "$UPDATE" = 1 ]; then
    echo "$STATS" > "$REF"
    echo "    wrote reference: $REF"
    echo "    events=$EVENTS charge_sum=$CHARGE_SUM"
elif [ ! -f "$REF" ]; then
    echo "    SKIP: no reference at $REF (create it with --update)"
elif [ "$STATS" = "$(cat "$REF")" ]; then
    echo "    PASS  events=$EVENTS charge_sum=$CHARGE_SUM"
else
    echo "    FAIL  got      $STATS"
    echo "          expected $(cat "$REF")"
    FAILED=1
fi

echo "--- 2. one electron per ionization event"
if [ "$EVENTS" -eq 0 ]; then
    echo "    FAIL  no ionization happened - the pulse is outside the run window,"
    echo "          so checks 1 and 4 would pass while testing nothing"
    FAILED=1
elif [ "$CHARGE_SUM" = "$EVENTS" ]; then
    echo "    PASS  sum(charges) = $CHARGE_SUM = events"
else
    echo "    FAIL  sum(charges) = $CHARGE_SUM, events = $EVENTS"
    FAILED=1
fi

echo "--- 3. no -ionize writes no ionization output"
rm -rf simulation_output
run "$BINDIR/mdrun" -deffnm plain -s run.tpr -nt 1
if [ -d simulation_output ]; then
    echo "    FAIL  simulation_output/ was created without -ionize"
    FAILED=1
else
    echo "    PASS"
fi

echo "--- 4. -nt 4 -pd is reproducible with a pinned seed"
for r in a b; do
    rm -rf simulation_output; mkdir -p simulation_output
    run "$BINDIR/mdrun" -deffnm "pd_$r" -s run.tpr -nt 4 -pd -ionize
    cp simulation_output/charges.txt "charges_pd_$r.txt"
done
if cmp -s charges_pd_a.txt charges_pd_b.txt; then
    echo "    PASS  identical across two -nt 4 -pd runs"
else
    echo "    FAIL  two -nt 4 -pd runs with the same seed differ"
    FAILED=1
fi

echo
if [ "$FAILED" = 0 ]; then echo "OK"; else echo "FAILURES"; KEEP=1; fi
exit $FAILED
